# project_id will be set dynamically by deployment scripts
# Dev: jhelkawgkjohvzsusrnw
# Prod: imncjxfppzikerifyukk
project_id = ""

[functions.invite-bank-viewer]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.complete-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generate-image-description]
enabled = true
verify_jwt = true
import_map = "./functions/generate-image-description/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-image-description/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-image-description/*.html" ]
